uri: ${vcap.services.git.credentials.uri}
username: ${vcap.services.git.credentials.username}
password: ${vcap.services.git.credentials.password}
---
spring:
  cloud:
    config:
      server:
        git:
          uri: ${uri}
security:
  user:
    name: ${username}
    password: ${password}
