---
# this manifest deploys the rsoter application
applications:
  - name: configserver
    memory: 1G
    instances: 1
    buildpack: java_buildpack
    services:
      - config-repo
      - configLogs
    env:
      SPRING_PROFILES_ACTIVE: cloud
