uri: ${vcap.services.github.credentials.username}
username: ${vcap.services.github.credentials.username}
password: ${vcap.services.github.credentials.password}
---
spring:
  cloud:
    config:
      server:
        git:
          uri: github.com
          username: {username}
          password: {password}
security:
  user:
    name: {username}
    password: {password}
